What we are doing...
import 
numpy 
pandas 
matplotlib
seaborn 

Load csv for olympics.csv dataset 
check the head 

look at descriptive statistics and info about it

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_csv('olympics.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !,02 !,03 !,Total,№ Games,01 !,02 !,03 !,Combined total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       147 non-null    object
 1   1       148 non-null    object
 2   2       148 non-null    object
 3   3       148 non-null    object
 4   4       148 non-null    object
 5   5       148 non-null    object
 6   6       148 non-null    object
 7   7       148 non-null    object
 8   8       148 non-null    object
 9   9       148 non-null    object
 10  10      148 non-null    object
 11  11      148 non-null    object
 12  12      148 non-null    object
 13  13      148 non-null    object
 14  14      148 non-null    object
 15  15      148 non-null    object
dtypes: object(16)
memory usage: 18.6+ KB

In [4]:
# Rename columns
df.columns = ['Country', 'Summer Games', 'Summer Gold', 'Summer Silver', 'Summer Bronze', 'Summer Total',
              'Winter Games', 'Winter Gold', 'Winter Silver', 'Winter Bronze', 'Winter Total',
              'Total Games', 'Total Gold', 'Total Silver', 'Total Bronze', 'Combined Total']

# Drop rows with any NaN
df = df.dropna()

# Convert each column to int
df['Summer Games'] = pd.to_numeric(df['Summer Games'], errors='coerce').astype('int64')
df['Summer Gold'] = pd.to_numeric(df['Summer Gold'], errors='coerce').astype('int64')
df['Summer Silver'] = pd.to_numeric(df['Summer Silver'], errors='coerce').astype('int64')
df['Summer Bronze'] = pd.to_numeric(df['Summer Bronze'], errors='coerce').astype('int64')
df['Summer Total'] = pd.to_numeric(df['Summer Total'], errors='coerce').astype('int64')
df['Winter Games'] = pd.to_numeric(df['Winter Games'], errors='coerce').astype('int64')
df['Winter Gold'] = pd.to_numeric(df['Winter Gold'], errors='coerce').astype('int64')
df['Winter Silver'] = pd.to_numeric(df['Winter Silver'], errors='coerce').astype('int64')
df['Winter Bronze'] = pd.to_numeric(df['Winter Bronze'], errors='coerce').astype('int64')
df['Winter Total'] = pd.to_numeric(df['Winter Total'], errors='coerce').astype('int64')
df['Total Games'] = pd.to_numeric(df['Total Games'], errors='coerce').astype('int64')
df['Total Gold'] = pd.to_numeric(df['Total Gold'], errors='coerce').astype('int64')
df['Total Silver'] = pd.to_numeric(df['Total Silver'], errors='coerce').astype('int64')
df['Total Bronze'] = pd.to_numeric(df['Total Bronze'], errors='coerce').astype('int64')
df['Combined Total'] = pd.to_numeric(df['Combined Total'], errors='coerce').astype('int64')

df.head()

,Country,Summer Games,Summer Gold,Summer Silver,Summer Bronze,Summer Total,Winter Games,Winter Gold,Winter Silver,Winter Bronze,Winter Total,Total Games,Total Gold,Total Silver,Total Bronze,Combined Total
1,Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
2,Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
3,Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
4,Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
5,Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [5]:
df.set_index("Country", inplace=True)

In [6]:
df.astype('Int64')

,Summer Games,Summer Gold,Summer Silver,Summer Bronze,Summer Total,Winter Games,Winter Gold,Winter Silver,Winter Bronze,Winter Total,Total Games,Total Gold,Total Silver,Total Bronze,Combined Total
Country,,,,,,,,,,,,,,,
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Independent Olympic Participants (IOP) [IOP],1,0,1,2,3,0,0,0,0,0,1,0,1,2,3
Zambia (ZAM) [ZAM],12,0,1,1,2,0,0,0,0,0,12,0,1,1,2
Zimbabwe (ZIM) [ZIM],12,3,4,1,8,1,0,0,0,0,13,3,4,1,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, Afghanistan (AFG) to Totals
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Summer Games    147 non-null    int64
 1   Summer Gold     147 non-null    int64
 2   Summer Silver   147 non-null    int64
 3   Summer Bronze   147 non-null    int64
 4   Summer Total    147 non-null    int64
 5   Winter Games    147 non-null    int64
 6   Winter Gold     147 non-null    int64
 7   Winter Silver   147 non-null    int64
 8   Winter Bronze   147 non-null    int64
 9   Winter Total    147 non-null    int64
 10  Total Games     147 non-null    int64
 11  Total Gold      147 non-null    int64
 12  Total Silver    147 non-null    int64
 13  Total Bronze    147 non-null    int64
 14  Combined Total  147 non-null    int64
dtypes: int64(15)
memory usage: 18.4+ KB

In [8]:
df.iloc[0]

Summer Games      13
Summer Gold        0
Summer Silver      0
Summer Bronze      2
Summer Total       2
Winter Games       0
Winter Gold        0
Winter Silver      0
Winter Bronze      0
Winter Total       0
Total Games       13
Total Gold         0
Total Silver       0
Total Bronze       2
Combined Total     2
Name: Afghanistan (AFG), dtype: int64

In [9]:
df.describe()

,Summer Games,Summer Gold,Summer Silver,Summer Bronze,Summer Total,Winter Games,Winter Gold,Winter Silver,Winter Bronze,Winter Total,Total Games,Total Gold,Total Silver,Total Bronze,Combined Total
count,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000,147.000000
mean,13.476190,65.428571,64.965986,69.795918,200.190476,6.700680,13.047619,13.034014,12.897959,38.979592,20.176871,78.476190,78.000000,82.693878,239.170068
std,7.072359,405.549990,399.309960,427.187344,1231.306297,7.433186,80.799204,80.634421,79.588388,240.917324,13.257048,485.013378,478.860334,505.855110,1469.067883
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.000000,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,1.000000,1.000000,2.500000
50%,13.000000,3.000000,4.000000,6.000000,12.000000,5.000000,0.000000,0.000000,0.000000,0.000000,15.000000,3.000000,4.000000,7.000000,12.000000
75%,18.500000,24.000000,28.000000,29.000000,86.000000,10.000000,1.000000,2.000000,1.000000,5.000000,27.000000,25.500000,29.000000,32.500000,89.000000
max,27.000000,4809.000000,4775.000000,5130.000000,14714.000000,22.000000,959.000000,958.000000,948.000000,2865.000000,49.000000,5768.000000,5733.000000,6078.000000,17579.000000

In [10]:
# which country has the most gold in the winter and bronze in the summer
# and then
# most metals per apearance make a column that has the most metals per apearance
# and then 
# if gold is 3, silver is 2, and bronz is 1 give a total number of points for each.

In [18]:
# Which country has the most gold in winter
most_winter_gold_country = df['Winter Gold'].idxmax()
most_winter_gold_value = df['Winter Gold'].max()

print(f"Country with most Winter Gold: {most_winter_gold_country} ({most_winter_gold_value} gold medals)")

# Which country has the most bronze in summer
most_summer_bronze_country = df['Summer Bronze'].idxmax()
most_summer_bronze_value = df['Summer Bronze'].max()
print(f"Country with most Summer Bronze: {most_summer_bronze_country} ({most_summer_bronze_value} bronze medals)")

Country with most Winter Gold: Totals (959 gold medals)
Country with most Summer Bronze: Totals (5130 bronze medals)

In [12]:
# Most metals per appearance (Total medals / Total Games)
df['Metals per Appearance'] = df['Combined Total'] / df['Total Games']
most_metals_per_appearance = df['Metals per Appearance'].idxmax()
most_metals_value = df['Metals per Appearance'].max()
print(f"Country with most metals per appearance: {most_metals_per_appearance} ({most_metals_value:.2f} medals per game)")
df.head()

Country with most metals per appearance: Totals (358.76 medals per game)

,Summer Games,Summer Gold,Summer Silver,Summer Bronze,Summer Total,Winter Games,Winter Gold,Winter Silver,Winter Bronze,Winter Total,Total Games,Total Gold,Total Silver,Total Bronze,Combined Total,Metals per Appearance
Country,,,,,,,,,,,,,,,,
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,0.153846
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,1.000000
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,1.707317
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,1.090909
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,6.000000

In [13]:
# Points system: Gold=3, Silver=2, Bronze=1
df['Total Points'] = (df['Total Gold'] * 3) + (df['Total Silver'] * 2) + (df['Total Bronze'] * 1)
df['Summer Points'] = (df['Summer Gold'] * 3) + (df['Summer Silver'] * 2) + (df['Summer Bronze'] * 1)
df['Winter Points'] = (df['Winter Gold'] * 3) + (df['Winter Silver'] * 2) + (df['Winter Bronze'] * 1)

# Show top countries by total points
top_points = df.sort_values('Total Points', ascending=False).head(10)
print(top_points[['Total Points', 'Summer Points', 'Winter Points']])

                                     Total Points  Summer Points  \
Country
Totals                                      34848          29107
United States (USA) [P] [Q] [R] [Z]          5684           5108
Soviet Union (URS) [URS]                     2526           2119
Great Britain (GBR) [GBR] [Z]                1574           1524
Germany (GER) [GER] [Z]                      1546           1103
France (FRA) [O] [P] [Z]                     1500           1298
Italy (ITA) [M] [S]                          1333           1111
Sweden (SWE) [Z]                             1217            933
China (CHN) [CHN]                            1120           1021
East Germany (GDR) [GDR]                     1068            844

                                     Winter Points
Country
Totals                                        5741
United States (USA) [P] [Q] [R] [Z]            576
Soviet Union (URS) [URS]                       407
Great Britain (GBR) [GBR] [Z]                   50
Germany (GER) [GER] [Z]                        443
France (FRA) [O] [P] [Z]                       202
Italy (ITA) [M] [S]                            222
Sweden (SWE) [Z]                               284
China (CHN) [CHN]                               99
East Germany (GDR) [GDR]                       224

In [19]:
df_titanic=sns.load_dataset("titanic")

In [20]:
df_titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [26]:
df_titanic.groupby("class")

In [ ]:
# what are the survual rates on each class